### ISSUE TITLE
Connect New Play Page to Backend

### ISSUE THREAD

**Issue by kheff16** [ucsb-cs156-w22/demo-spring-react-example-v2#41]
In this issue, we take the placeholder page from issue #18, and we add in the components developed in issues #19 #20 #21 and implement a full play page similar to this one, that is fully functional with the backend.  

<img width="1027" alt="HappyCowsPlayPage" src="https://user-images.githubusercontent.com/1119017/117352663-18be0100-ae64-11eb-8fab-e5fe59531a7c.png">

From issue #18, the page just displayed the `Welcome Farmer ${firstname}` text, and nothing more.   

In this issue, we add the various separately developed components from #19, #20, #23, #21 to the page.

# Acceptance Criteria

- [ ] This page is in the storybook, with an example of what it looks like with fixture data
- [ ] This page displays the component`Overview` (renamed from "Announcements" at the top from #19 )
- [ ] Displays the component `ManageCows` from #20 at bottom left
- [ ] Displays the component `YourFarmStats` from #23 at bottom center
- [ ] Displays the component `YourProfits` from #21 at bottom right

# When component is in the Storybook and has good test coverage: if the backend is ready

# Implementation notes:

- [ ] ADD ADDITIONAL ACs here for making the component actually work with the backend.
