### ISSUE TITLE
UCSBStudent epic

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w22/demo-spring-react-example-v2#78]
Using UCSBDate as a model, but now adapting as needed for the fact that we are storing entries in a MongoDB database, implement CRUD operations for Students

- [ ] Add Students menu that shows up only when logged in; has only one item for regular users (List) and two items for Admin users (List and Create).   Goes to placeholder pages.
- [ ] Make a reusable StudentsTable component and add to Storybook
- [ ] Make the List page (aka index page) work (no Edit or Delete buttons yet)
- [ ] Make a reusable StudentForm and add to Storybook
- [ ] Make the Create page for Student work 
- [ ] Add a delete button so that Students can be deleted.
- [ ] Add an edit button so that Students can be edited.
